//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumoWS.Servicios {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Equipos", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Equipos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreEquipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string paisField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string nombreEquipo {
            get {
                return this.nombreEquipoField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreEquipoField, value) != true)) {
                    this.nombreEquipoField = value;
                    this.RaisePropertyChanged("nombreEquipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string pais {
            get {
                return this.paisField;
            }
            set {
                if ((object.ReferenceEquals(this.paisField, value) != true)) {
                    this.paisField = value;
                    this.RaisePropertyChanged("pais");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Servicios.ServiciosSoap")]
    public interface ServiciosSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        ConsumoWS.Servicios.HelloWorldResponse HelloWorld(ConsumoWS.Servicios.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumoWS.Servicios.HelloWorldResponse> HelloWorldAsync(ConsumoWS.Servicios.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name nombre from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Saludar", ReplyAction="*")]
        ConsumoWS.Servicios.SaludarResponse Saludar(ConsumoWS.Servicios.SaludarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Saludar", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumoWS.Servicios.SaludarResponse> SaludarAsync(ConsumoWS.Servicios.SaludarRequest request);
        
        // CODEGEN: Generating message contract since element name texto from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GuardarLog", ReplyAction="*")]
        ConsumoWS.Servicios.GuardarLogResponse GuardarLog(ConsumoWS.Servicios.GuardarLogRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GuardarLog", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumoWS.Servicios.GuardarLogResponse> GuardarLogAsync(ConsumoWS.Servicios.GuardarLogRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Multiplicacion", ReplyAction="*")]
        int Multiplicacion(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Multiplicacion", ReplyAction="*")]
        System.Threading.Tasks.Task<int> MultiplicacionAsync(int a, int b);
        
        // CODEGEN: Generating message contract since element name ObtenerDeportesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerDeportes", ReplyAction="*")]
        ConsumoWS.Servicios.ObtenerDeportesResponse ObtenerDeportes(ConsumoWS.Servicios.ObtenerDeportesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerDeportes", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumoWS.Servicios.ObtenerDeportesResponse> ObtenerDeportesAsync(ConsumoWS.Servicios.ObtenerDeportesRequest request);
        
        // CODEGEN: Generating message contract since element name deportes from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GuardarVector", ReplyAction="*")]
        ConsumoWS.Servicios.GuardarVectorResponse GuardarVector(ConsumoWS.Servicios.GuardarVectorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GuardarVector", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumoWS.Servicios.GuardarVectorResponse> GuardarVectorAsync(ConsumoWS.Servicios.GuardarVectorRequest request);
        
        // CODEGEN: Generating message contract since element name ObptenrEquiposResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObptenrEquipos", ReplyAction="*")]
        ConsumoWS.Servicios.ObptenrEquiposResponse ObptenrEquipos(ConsumoWS.Servicios.ObptenrEquiposRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObptenrEquipos", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumoWS.Servicios.ObptenrEquiposResponse> ObptenrEquiposAsync(ConsumoWS.Servicios.ObptenrEquiposRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public ConsumoWS.Servicios.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ConsumoWS.Servicios.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsumoWS.Servicios.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ConsumoWS.Servicios.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaludarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Saludar", Namespace="http://tempuri.org/", Order=0)]
        public ConsumoWS.Servicios.SaludarRequestBody Body;
        
        public SaludarRequest() {
        }
        
        public SaludarRequest(ConsumoWS.Servicios.SaludarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaludarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        public SaludarRequestBody() {
        }
        
        public SaludarRequestBody(string nombre) {
            this.nombre = nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaludarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaludarResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsumoWS.Servicios.SaludarResponseBody Body;
        
        public SaludarResponse() {
        }
        
        public SaludarResponse(ConsumoWS.Servicios.SaludarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaludarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SaludarResult;
        
        public SaludarResponseBody() {
        }
        
        public SaludarResponseBody(string SaludarResult) {
            this.SaludarResult = SaludarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GuardarLogRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GuardarLog", Namespace="http://tempuri.org/", Order=0)]
        public ConsumoWS.Servicios.GuardarLogRequestBody Body;
        
        public GuardarLogRequest() {
        }
        
        public GuardarLogRequest(ConsumoWS.Servicios.GuardarLogRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GuardarLogRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string texto;
        
        public GuardarLogRequestBody() {
        }
        
        public GuardarLogRequestBody(string texto) {
            this.texto = texto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GuardarLogResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GuardarLogResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsumoWS.Servicios.GuardarLogResponseBody Body;
        
        public GuardarLogResponse() {
        }
        
        public GuardarLogResponse(ConsumoWS.Servicios.GuardarLogResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GuardarLogResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GuardarLogResult;
        
        public GuardarLogResponseBody() {
        }
        
        public GuardarLogResponseBody(string GuardarLogResult) {
            this.GuardarLogResult = GuardarLogResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerDeportesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerDeportes", Namespace="http://tempuri.org/", Order=0)]
        public ConsumoWS.Servicios.ObtenerDeportesRequestBody Body;
        
        public ObtenerDeportesRequest() {
        }
        
        public ObtenerDeportesRequest(ConsumoWS.Servicios.ObtenerDeportesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ObtenerDeportesRequestBody {
        
        public ObtenerDeportesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerDeportesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerDeportesResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsumoWS.Servicios.ObtenerDeportesResponseBody Body;
        
        public ObtenerDeportesResponse() {
        }
        
        public ObtenerDeportesResponse(ConsumoWS.Servicios.ObtenerDeportesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerDeportesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsumoWS.Servicios.ArrayOfString ObtenerDeportesResult;
        
        public ObtenerDeportesResponseBody() {
        }
        
        public ObtenerDeportesResponseBody(ConsumoWS.Servicios.ArrayOfString ObtenerDeportesResult) {
            this.ObtenerDeportesResult = ObtenerDeportesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GuardarVectorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GuardarVector", Namespace="http://tempuri.org/", Order=0)]
        public ConsumoWS.Servicios.GuardarVectorRequestBody Body;
        
        public GuardarVectorRequest() {
        }
        
        public GuardarVectorRequest(ConsumoWS.Servicios.GuardarVectorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GuardarVectorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsumoWS.Servicios.ArrayOfString deportes;
        
        public GuardarVectorRequestBody() {
        }
        
        public GuardarVectorRequestBody(ConsumoWS.Servicios.ArrayOfString deportes) {
            this.deportes = deportes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GuardarVectorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GuardarVectorResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsumoWS.Servicios.GuardarVectorResponseBody Body;
        
        public GuardarVectorResponse() {
        }
        
        public GuardarVectorResponse(ConsumoWS.Servicios.GuardarVectorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GuardarVectorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GuardarVectorResult;
        
        public GuardarVectorResponseBody() {
        }
        
        public GuardarVectorResponseBody(string GuardarVectorResult) {
            this.GuardarVectorResult = GuardarVectorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObptenrEquiposRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObptenrEquipos", Namespace="http://tempuri.org/", Order=0)]
        public ConsumoWS.Servicios.ObptenrEquiposRequestBody Body;
        
        public ObptenrEquiposRequest() {
        }
        
        public ObptenrEquiposRequest(ConsumoWS.Servicios.ObptenrEquiposRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ObptenrEquiposRequestBody {
        
        public ObptenrEquiposRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObptenrEquiposResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObptenrEquiposResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsumoWS.Servicios.ObptenrEquiposResponseBody Body;
        
        public ObptenrEquiposResponse() {
        }
        
        public ObptenrEquiposResponse(ConsumoWS.Servicios.ObptenrEquiposResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObptenrEquiposResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsumoWS.Servicios.Equipos[] ObptenrEquiposResult;
        
        public ObptenrEquiposResponseBody() {
        }
        
        public ObptenrEquiposResponseBody(ConsumoWS.Servicios.Equipos[] ObptenrEquiposResult) {
            this.ObptenrEquiposResult = ObptenrEquiposResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiciosSoapChannel : ConsumoWS.Servicios.ServiciosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiciosSoapClient : System.ServiceModel.ClientBase<ConsumoWS.Servicios.ServiciosSoap>, ConsumoWS.Servicios.ServiciosSoap {
        
        public ServiciosSoapClient() {
        }
        
        public ServiciosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiciosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiciosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiciosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumoWS.Servicios.HelloWorldResponse ConsumoWS.Servicios.ServiciosSoap.HelloWorld(ConsumoWS.Servicios.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ConsumoWS.Servicios.HelloWorldRequest inValue = new ConsumoWS.Servicios.HelloWorldRequest();
            inValue.Body = new ConsumoWS.Servicios.HelloWorldRequestBody();
            ConsumoWS.Servicios.HelloWorldResponse retVal = ((ConsumoWS.Servicios.ServiciosSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumoWS.Servicios.HelloWorldResponse> ConsumoWS.Servicios.ServiciosSoap.HelloWorldAsync(ConsumoWS.Servicios.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumoWS.Servicios.HelloWorldResponse> HelloWorldAsync() {
            ConsumoWS.Servicios.HelloWorldRequest inValue = new ConsumoWS.Servicios.HelloWorldRequest();
            inValue.Body = new ConsumoWS.Servicios.HelloWorldRequestBody();
            return ((ConsumoWS.Servicios.ServiciosSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumoWS.Servicios.SaludarResponse ConsumoWS.Servicios.ServiciosSoap.Saludar(ConsumoWS.Servicios.SaludarRequest request) {
            return base.Channel.Saludar(request);
        }
        
        public string Saludar(string nombre) {
            ConsumoWS.Servicios.SaludarRequest inValue = new ConsumoWS.Servicios.SaludarRequest();
            inValue.Body = new ConsumoWS.Servicios.SaludarRequestBody();
            inValue.Body.nombre = nombre;
            ConsumoWS.Servicios.SaludarResponse retVal = ((ConsumoWS.Servicios.ServiciosSoap)(this)).Saludar(inValue);
            return retVal.Body.SaludarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumoWS.Servicios.SaludarResponse> ConsumoWS.Servicios.ServiciosSoap.SaludarAsync(ConsumoWS.Servicios.SaludarRequest request) {
            return base.Channel.SaludarAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumoWS.Servicios.SaludarResponse> SaludarAsync(string nombre) {
            ConsumoWS.Servicios.SaludarRequest inValue = new ConsumoWS.Servicios.SaludarRequest();
            inValue.Body = new ConsumoWS.Servicios.SaludarRequestBody();
            inValue.Body.nombre = nombre;
            return ((ConsumoWS.Servicios.ServiciosSoap)(this)).SaludarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumoWS.Servicios.GuardarLogResponse ConsumoWS.Servicios.ServiciosSoap.GuardarLog(ConsumoWS.Servicios.GuardarLogRequest request) {
            return base.Channel.GuardarLog(request);
        }
        
        public string GuardarLog(string texto) {
            ConsumoWS.Servicios.GuardarLogRequest inValue = new ConsumoWS.Servicios.GuardarLogRequest();
            inValue.Body = new ConsumoWS.Servicios.GuardarLogRequestBody();
            inValue.Body.texto = texto;
            ConsumoWS.Servicios.GuardarLogResponse retVal = ((ConsumoWS.Servicios.ServiciosSoap)(this)).GuardarLog(inValue);
            return retVal.Body.GuardarLogResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumoWS.Servicios.GuardarLogResponse> ConsumoWS.Servicios.ServiciosSoap.GuardarLogAsync(ConsumoWS.Servicios.GuardarLogRequest request) {
            return base.Channel.GuardarLogAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumoWS.Servicios.GuardarLogResponse> GuardarLogAsync(string texto) {
            ConsumoWS.Servicios.GuardarLogRequest inValue = new ConsumoWS.Servicios.GuardarLogRequest();
            inValue.Body = new ConsumoWS.Servicios.GuardarLogRequestBody();
            inValue.Body.texto = texto;
            return ((ConsumoWS.Servicios.ServiciosSoap)(this)).GuardarLogAsync(inValue);
        }
        
        public int Multiplicacion(int a, int b) {
            return base.Channel.Multiplicacion(a, b);
        }
        
        public System.Threading.Tasks.Task<int> MultiplicacionAsync(int a, int b) {
            return base.Channel.MultiplicacionAsync(a, b);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumoWS.Servicios.ObtenerDeportesResponse ConsumoWS.Servicios.ServiciosSoap.ObtenerDeportes(ConsumoWS.Servicios.ObtenerDeportesRequest request) {
            return base.Channel.ObtenerDeportes(request);
        }
        
        public ConsumoWS.Servicios.ArrayOfString ObtenerDeportes() {
            ConsumoWS.Servicios.ObtenerDeportesRequest inValue = new ConsumoWS.Servicios.ObtenerDeportesRequest();
            inValue.Body = new ConsumoWS.Servicios.ObtenerDeportesRequestBody();
            ConsumoWS.Servicios.ObtenerDeportesResponse retVal = ((ConsumoWS.Servicios.ServiciosSoap)(this)).ObtenerDeportes(inValue);
            return retVal.Body.ObtenerDeportesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumoWS.Servicios.ObtenerDeportesResponse> ConsumoWS.Servicios.ServiciosSoap.ObtenerDeportesAsync(ConsumoWS.Servicios.ObtenerDeportesRequest request) {
            return base.Channel.ObtenerDeportesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumoWS.Servicios.ObtenerDeportesResponse> ObtenerDeportesAsync() {
            ConsumoWS.Servicios.ObtenerDeportesRequest inValue = new ConsumoWS.Servicios.ObtenerDeportesRequest();
            inValue.Body = new ConsumoWS.Servicios.ObtenerDeportesRequestBody();
            return ((ConsumoWS.Servicios.ServiciosSoap)(this)).ObtenerDeportesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumoWS.Servicios.GuardarVectorResponse ConsumoWS.Servicios.ServiciosSoap.GuardarVector(ConsumoWS.Servicios.GuardarVectorRequest request) {
            return base.Channel.GuardarVector(request);
        }
        
        public string GuardarVector(ConsumoWS.Servicios.ArrayOfString deportes) {
            ConsumoWS.Servicios.GuardarVectorRequest inValue = new ConsumoWS.Servicios.GuardarVectorRequest();
            inValue.Body = new ConsumoWS.Servicios.GuardarVectorRequestBody();
            inValue.Body.deportes = deportes;
            ConsumoWS.Servicios.GuardarVectorResponse retVal = ((ConsumoWS.Servicios.ServiciosSoap)(this)).GuardarVector(inValue);
            return retVal.Body.GuardarVectorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumoWS.Servicios.GuardarVectorResponse> ConsumoWS.Servicios.ServiciosSoap.GuardarVectorAsync(ConsumoWS.Servicios.GuardarVectorRequest request) {
            return base.Channel.GuardarVectorAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumoWS.Servicios.GuardarVectorResponse> GuardarVectorAsync(ConsumoWS.Servicios.ArrayOfString deportes) {
            ConsumoWS.Servicios.GuardarVectorRequest inValue = new ConsumoWS.Servicios.GuardarVectorRequest();
            inValue.Body = new ConsumoWS.Servicios.GuardarVectorRequestBody();
            inValue.Body.deportes = deportes;
            return ((ConsumoWS.Servicios.ServiciosSoap)(this)).GuardarVectorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumoWS.Servicios.ObptenrEquiposResponse ConsumoWS.Servicios.ServiciosSoap.ObptenrEquipos(ConsumoWS.Servicios.ObptenrEquiposRequest request) {
            return base.Channel.ObptenrEquipos(request);
        }
        
        public ConsumoWS.Servicios.Equipos[] ObptenrEquipos() {
            ConsumoWS.Servicios.ObptenrEquiposRequest inValue = new ConsumoWS.Servicios.ObptenrEquiposRequest();
            inValue.Body = new ConsumoWS.Servicios.ObptenrEquiposRequestBody();
            ConsumoWS.Servicios.ObptenrEquiposResponse retVal = ((ConsumoWS.Servicios.ServiciosSoap)(this)).ObptenrEquipos(inValue);
            return retVal.Body.ObptenrEquiposResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumoWS.Servicios.ObptenrEquiposResponse> ConsumoWS.Servicios.ServiciosSoap.ObptenrEquiposAsync(ConsumoWS.Servicios.ObptenrEquiposRequest request) {
            return base.Channel.ObptenrEquiposAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumoWS.Servicios.ObptenrEquiposResponse> ObptenrEquiposAsync() {
            ConsumoWS.Servicios.ObptenrEquiposRequest inValue = new ConsumoWS.Servicios.ObptenrEquiposRequest();
            inValue.Body = new ConsumoWS.Servicios.ObptenrEquiposRequestBody();
            return ((ConsumoWS.Servicios.ServiciosSoap)(this)).ObptenrEquiposAsync(inValue);
        }
    }
}
